### ISSUE TITLE
The agent was stopped due to either an iteration limit or a time limit. Api TELEGRAM

### ISSUE THREAD

**Issue by stebou** [joaomdmoura/crewAI#393]
Hey Crew AI Team 👋,

I'm diving into a project where I'm leveraging Crew AI to orchestrate automated agents for analyzing and processing information. I'm truly amazed by what you've built, and I'm super excited about tapping into the full potential of Crew AI! However, I've hit a couple of snags, especially in connection with the Telegram API, and I could really use your insight.

Here's what's happening:

Iteration and Time Limits: My agents, tasked with conducting thorough research, often hit iteration or time limits before they can complete their tasks. As a result, my users end up waiting for answers that, unfortunately, don't come.

Response Times with the Telegram API: When my agents try to interact with the Telegram API, things slow down quite a bit. I believe the API's response times are a bit longer than I had anticipated, which leads to delays and sometimes even service interruptions.

Impact:

This is making the user experience less smooth and a bit frustrating since they're not always getting the info they're looking for.
I find myself in a bit of a bind, unable to provide the complete and precise info that would make my bot truly useful.
What I'm looking to do:

I'm exploring ways to optimize my agents' tasks, adjust the limits imposed on them, and enhance how I handle exceptions to make everything more seamless. Additionally, I'm seeking advice on improving my interactions with the Telegram API to reduce these notable delays.

I genuinely love working with Crew AI, and I'm convinced that with a little help, I can overcome these issues and make my bot even more awesome. If you have any suggestions, advice, or best practices to share, I'm all ears!

Thanks a million for your help and for creating such a fantastic tool. I'm looking forward to seeing how I can make my project even better with your support.

Warm regards,

**Comment by aliensouls** [comment]
did you try the 
```
            max_rpm=10
            max_iter=10
``` 
these are the only controls for iterations and rpm afaik. 
I'm getting same error but even when I run much below the limits, don't know how to debug it..

**Comment by aliensouls** [comment]
I turned off "memory" of the agent and also raised `max_iter` , I suspect the agent remembered that it already attempted to answer the same query, so I suspect the memory flag has something to do with it, or maybe just the iterations 🤔 not sure if they persist over restarts of the script or not, if memory is enabled.

**Comment by stebou** [comment]
i resolve the probleme i have used a library named praisonai and add tools and it'sword, i have tested max_rpm and max-iter but it doesn't work, thanks for response @aliensouls

**Comment by Neethan54** [comment]
Hi @stebou , can you tell us , how did you use praisonai  in the tools of agents ?

**Comment by stebou** [comment]
Hello go to se this vidéo, https://youtu.be/XaQRgRpV7jo?si=m5Y6ID_KNi2LwDli

**Comment by joaomdmoura** [comment]
@stebou as suggested,  Max Iter and Max RPM are the way to go, I see you mention time was also a constrain so we will be adding that as an extra option.

Max Iter (optional)	
> The maximum number of iterations the agent can perform before being forced to give its best answer. Default is 15.`

Max RPM (optional)
> The maximum number of requests per minute the agent can perform to avoid rate limits. It's optional and can be left unspecified, with a default value of None.

**Comment by joaomdmoura** [comment]
Just launched `0.27.2` where agents now also have `max_execution_time` so you don't need the extra dependency if you don't need to

**Comment by TechDom** [comment]
**Could you explain what `max_iter` actually means and does?** What is considered an iteration here?

I am running into the same issue, also on `v0.27.2` (thanks for that btw! :)). I found that if i increase `max_iter` (e.g. to 15), then it just takes longer and longer (minutes, the LLM server is quite slow) to eventually still get the same error as if I had set it to just 1 or 2: `[DEBUG]: == [Analyzer] Task output: Agent stopped due to iteration limit or time limit.` This appears to be independent of my input length, i.e. I get the same error when I input a few hundred tokens vs just a handful of them.

Increasing `max_execution_time` did not seem to make a difference here.

**Comment by joaomdmoura** [comment]
So I'd love to see more of the actual code, if you can share, the iteration referes to the inner thought process of the agents, like choosing to use a tool or not for example. the way it works is that as it get closes to that iteration limit we theoretically for the LLM to give an answer but it seesm that might not be happening in this case so if you could share move even if privately it might help us replicate and fix the bug

**Comment by TechDom** [comment]
Of course. This is the code I am using:
```python
import os
from crewai import Agent, Task, Crew
import openai
from langchain.chat_models import ChatOpenAI
from langchain.globals import set_debug
set_debug(True)


LLM_HOST = f"http://<host>:<port>/v1" # url ommitted
os.environ["OPENAI_API_KEY"] = "NA"

model = ChatOpenAI(
    model="llama-13b.Q5_K_M.gguf",
    openai_api_base=LLM_HOST,
    max_tokens = 240,
    temperature= 0.5,
    streaming = True 
)

writer = Agent(
    role='Mathematician',
    goal='Help the world!',
    backstory="You are a mathematician and love to give short, consice answers.",
    allow_delegation=False,
    verbose=True,
    tools=[],
    memory=True,
    max_iter=2,
    llm=model
)

task = Task(
    description="Answer: What's 2+2?",
    agent=writer,
    expected_output="Provide the answer only."
)

crew =  Crew(
    agents=[writer],
    tasks=[task],
    verbose=True,
    memory=True,
    share_crew=False,
    telemetry=False
)
result = crew.kickoff()
print("### FINAL RESULT ###")
print(result)
```
it typically leads to the time/iterations limit error described before:
```bash
 [DEBUG]: == Working Agent: Document Query Specialist
 [INFO]: == Starting Task: Answer: What is 2+2?


> Entering new CrewAgentExecutor chain...


> Finished chain.
 [DEBUG]: == [Document Query Specialist] Task output: Agent stopped due to iteration limit or time limit.
```
The Llama model runs on a remote server and is deployed using llama.cpp server. The server might be slow, but returns the response within 20 seconds when prompted individually - the iterations/time limit only occurs after approx. 3 minutes.

---
There is another things that just appeared as I composed this message:
Unfortunately, and rather out of the blue, ChatOpenAI started giving me a `Incorrect API key provided: NA.` error and the above code exists prematurely. This hasn't happened before - when I create a ChatOpenAI instance without CrewAI, it works just fine (see code below). Not sure if this has anything to do with it, so far I think this is an unrelated issue. But just in case, here is the code that works just fine, without using crewAI:
```python
import os
from langchain.chat_models import ChatOpenAI

LLM_HOST = f"http://<host>:<port>/v1" # url ommitted
os.environ["OPENAI_API_KEY"] = "NA"

model = ChatOpenAI(
    model="llama-13b.Q5_K_M.gguf",
    openai_api_base=LLM_HOST,
    max_tokens = 240,
    temperature= 0.5,
    streaming = True 
)

res = model.invoke("Tell me something about cats!")
print(res)
```
by itself, it works fine.

**Comment by aliensouls** [comment]
Check your credits balance, because it throws same error text also when
credits are depleted despite iterations and everything is configured
correctly, happened to me as well - they have a "monthly limit" of 120$
let's say based on your tier (how much money so far you wasted on api) and
even when you top up, this monthly setting remains on old value so it still
won't work until you increase this number manually in your billing
settings. Might be your case, based on symptoms (since your iterations are
on 15 and it fails on 1st one as I understand).

**Comment by TechDom** [comment]
Thanks for your reply!
As a side note: the `os.environ["OPENAI_API_KEY"] = "NA"` is the actual code and not an ommited api key for the purpose of this github comment. I don't even have an OpenAI account, since I don't intend to use the Openai models. ChatOpenAI is only used as the wrapper here to connect to my own model hosted on my own remote server - which does work as intended when prompted individually as shown above (no API key error).

In my case it's probably best to move away from the OpenAI Wrapper alltoghether - it should be possible to pass a Langchain [CustomLLM](https://python.langchain.com/docs/modules/model_io/llms/custom_llm/) instance to the `llm` parameter of an `Agent`, shouldn't it? Will probably give that another try now :)

**Comment by TechDom** [comment]
@joaomdmoura Is an OpenAI key strictly necessary even if I don't use any OpenAI models or Wrappers? I have now adjusted my LLM wrapper to use only langchain, but I still get this error:

```python
import os
from crewai import Agent, Task, Crew
from langchain.globals import set_debug
from typing import Any, List, Mapping, Optional
from langchain.callbacks.manager import CallbackManagerForLLMRun
from langchain_core.language_models.llms import LLM
set_debug(True)

class MyLLM(LLM):
    """
    Custom LLM class that returns a plain string
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    @property
    def _llm_type(self) -> str:
        return "custom"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        chatbot=None,
    ) -> str:
        """
        For simplicity, returns a plain string
        """

        if stop is not None:
            raise ValueError("stop kwargs are not permitted")
        return "This is a dummy response and show that the function is working. Well done!"
    
llm = MyLLM()

writer = Agent(
    role='Mathematician',
    goal='Help the world!',
    backstory="You are a mathematician and love to give short, consice answers.",
    allow_delegation=False,
    verbose=True,
    tools=[],
    memory=True,
    max_iter=2,
    llm=llm,
    cache=False
)

task = Task(
    description="Answer: What's 2+2?",
    agent=writer,
    expected_output="Provide the answer only."
)

crew =  Crew(
    agents=[writer],
    tasks=[task],
    verbose=True,
    memory=True,
    share_crew=False,
    telemetry=False
)
result = crew.kickoff()
print("### FINAL RESULT ###")
print(result)
```

This results in `openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: fake. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`, originating all the way from `crew.kickoff()`.

Interestingly, it says that the currently used key has the value "fake", which I believe comes from [this](https://github.com/joaomdmoura/crewAI/commit/cf4138f385982667bc2a989cc599ceed88a3dc08) recent commit where the crewAI library manually sets the key to this value if not provided otherwise:

```python
...
def __init__(self, type, allow_reset=True, embedder_config=None):
    super().__init__()
    if (
        not os.getenv("OPENAI_API_KEY")
        and not os.getenv("OPENAI_BASE_URLl") == "https://api.openai.com/v1"
    ):
        os.environ["OPENAI_API_KEY"] = "fake"
...
```
