### ISSUE TITLE
is there any other project like crewai, which is open-sources but has little bug.

### ISSUE THREAD

**Issue by WindSmileValley** [joaomdmoura/crewAI#681]
(；′⌒`)

**Comment by syberkitten** [comment]
Dunno about number of bugs, but you have langgraph (from langchain) and Autogen from Microsoft , both opensource

**Comment by joaomdmoura** [comment]
hey @FengXiaoGu would love to hear about what bugs you're facing :) we are shipping fix as fast as we can for anything that get's flagged and we can replicate

**Comment by FengXiaoGu** [comment]
@joaomdmoura thanks. I am using Ollama with CrewAI. The function about "delegate work" seems dosen't work well. The wrong issues include "None type", "Co-work" and so on, just like in other issues. I tried replace some "co-worker" with "coworker", and the changes seem can be work partly. So, I guess some terms are not same in the whole code. And I am not sure is these the same issues in other models.

**Comment by FengXiaoGu** [comment]
@syberkitten  thanks. I  also use the Autogen, and it is not enough simplicity and friendly with Ollama. The Autogen may be better in the future, and I also be coding with it. I want  multi-autogen tools that  work like a team which may be like the Consensual Process in the CrewAI future work. I am eagerly awaiting the finishing of the Consensual Process.

**Comment by joaomdmoura** [comment]
@WindSmileValley I think a lot of what you are experiencing is due to model capabilities, smaller model will struggle with model complex tools, you might want to disable delegation for example or use a bigger model, I can look into replacing co-worker with coworker if that makes it any better, but I think smaller models will struggle with complex instructions.
I'll close the issue for now but down for keep the thread going, on any other issues we can fix or small adjustments we can do to make it better. We are working on a more complex docs update, but we introduced the ability for you to replace the whole inner prompts if you want to try that, and also provide system and regular prompt formatting in case your model performs better that way, if you want me I can add instruction in here while we are updating docs

**Comment by WindSmileValley** [comment]
@joaomdmoura I am very willing to use the new feature, could you please provide me with the instructions when you have the time? Additionally, when you mentioned smaller models, are you referring to models with parameters less than a certain number, such as 70b or something else?
